name: Airdrop Library Automation Pipeline

on:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours (optimized for API rate limits)
  workflow_dispatch:        # Manual trigger
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.10'
  DATABASE_PATH: 'api/database.json'
  MAX_AIRDROPS: 200

jobs:
  validate-sources:
    name: Validate Sources
    runs-on: ubuntu-latest
    timeout-minutes: 20
    outputs:
      sources_valid: ${{ steps.validation.outputs.valid }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          
      - name: Run source validation
        id: validation
        run: |
          if python scripts/validation.py test; then
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "valid=false" >> $GITHUB_OUTPUT
            exit 1
          fi

  scrape-data:
    name: Scrape & Process Data
    needs: validate-sources
    if: ${{ needs.validate-sources.outputs.sources_valid == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    strategy:
      matrix:
        retry: [1, 2, 3]
      max-parallel: 1
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Cache scraped data
        uses: actions/cache@v4
        with:
          path: |
            sources.json
            ${{ env.DATABASE_PATH }}
          key: ${{ runner.os }}-scraped-${{ hashFiles('scripts/*.py') }}
          
      - name: Run scraper (Attempt ${{ matrix.retry }})
        run: |
          python scripts/scrape_airdrops.py --max ${{ env.MAX_AIRDROPS }} --retry ${{ matrix.retry }}
          
      - name: Validate output
        run: |
          if [ ! -s sources.json ]; then
            echo "Error: Empty output file"
            exit 1
          fi
          
      - name: Archive raw data
        uses: actions/upload-artifact@v4
        with:
          name: raw-scraped-data-${{ github.run_id }}
          path: sources.json
          retention-days: 3

  update-database:
    name: Update Database
    needs: scrape-data
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      count: ${{ steps.process.outputs.count }}
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update && sudo apt-get install -y jq
          
      - name: Download scraped data
        uses: actions/download-artifact@v4
        with:
          name: raw-scraped-data-${{ github.run_id }}
          
      - name: Process data
        id: process
        run: |
          python scripts/database.py --prune --limit ${{ env.MAX_AIRDROPS }}
          count=$(jq '.airdrops | length' ${{ env.DATABASE_PATH }} 2>/dev/null || echo "0")
          echo "count=$count" >> $GITHUB_OUTPUT
          
      - name: Verify database
        run: |
          if [ ! -f "${{ env.DATABASE_PATH }}" ]; then
            echo "Error: Database file not found"
            exit 1
          fi
          count=$(jq '.airdrops | length' ${{ env.DATABASE_PATH }} 2>/dev/null || echo "0")
          if [ "$count" -eq 0 ]; then
            echo "Warning: Empty database, but continuing"
          else
            echo "Database contains $count airdrops"
          fi

  deploy:
    name: Deploy Updates
    needs: update-database
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global pull.rebase true
          
      - name: Pull latest changes
        run: |
          git fetch origin
          git reset --hard origin/main
        
      - name: Commit updates
        run: |
          # Only add files that exist
          files_to_add=""
          [ -f "sources.json" ] && files_to_add="$files_to_add sources.json"
          [ -f "${{ env.DATABASE_PATH }}" ] && files_to_add="$files_to_add ${{ env.DATABASE_PATH }}"
          [ -f "docs/assets/data.json" ] && files_to_add="$files_to_add docs/assets/data.json"
          
          if [ -n "$files_to_add" ]; then
            git add $files_to_add
            if ! git diff --quiet --staged; then
              git commit -m "Automated update: $(date +'%Y-%m-%d %H:%M UTC') [skip ci]"
              git push origin main
            else
              echo "No changes to commit"
            fi
          else
            echo "No files to commit"
          fi
             
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: true
          force_orphan: false
          
      - name: Trigger API rebuild
        if: github.ref == 'refs/heads/main'
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'api-update'
            })

  notify:
    name: Notification
    if: always()
    needs: [validate-sources, scrape-data, update-database, deploy]
    runs-on: ubuntu-latest
    
    steps:
      - name: Send Slack notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # Ensure this secret is set in your repository settings
          SLACK_COLOR: danger
          SLACK_TITLE: "🛑 Airdrop Update Failed"
          SLACK_MESSAGE: "Workflow ${{ github.workflow }} failed on ${{ github.ref }}"
          
      - name: Send success notification
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # Ensure this secret is set in your repository settings
          SLACK_COLOR: good
          SLACK_TITLE: "✅ Airdrop Update Complete"
          SLACK_MESSAGE: "Successfully updated ${{ needs.update-database.outputs.count }} airdrops"